import type { APIRoute } from "astro";

// Served at /robots.txt. Allows all crawlers and points them at the sitemap
// index (generated by @astrojs/sitemap). The sitemap URL is derived from the
// configured `site` so it cannot drift from astro.config.mjs.
export const GET: APIRoute = ({ site }) => {
  const sitemap = new URL("sitemap-index.xml", site);
  const body = `User-agent: *
Allow: /

Sitemap: ${sitemap.href}
`;
  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
